// Stamp the Content Security Policy (scripts/csp-policy.mjs — the single source
// of truth) into every deployed page's <head>.
//
//   node scripts/apply-csp.mjs          # apply / refresh
//   node scripts/apply-csp.mjs --check  # verify only; non-zero exit on drift
//
// Idempotent: re-running replaces the existing block rather than appending, so
// editing the policy and re-running is the supported workflow. The tag is
// inserted immediately after <meta charset>, which must come first, and before
// any other resource-loading tag so the policy is in force for everything the
// page pulls in.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildCsp, PRUNED_FROM_PRODUCTION, CSP_MARKER } from './csp-policy.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK_ONLY = process.argv.includes('--check');

const BLOCK = (csp) =>
  `<!-- ${CSP_MARKER} — generated by scripts/apply-csp.mjs from scripts/csp-policy.mjs.\n` +
  `     Do not hand-edit: run \`node scripts/apply-csp.mjs\` after changing the policy.\n` +
  `     Delivered as a meta tag because GitHub Pages cannot set headers; the\n` +
  `     header-only directives (frame-ancestors) come from Cloudflare. See docs/CSP.md. -->\n` +
  `<meta http-equiv="Content-Security-Policy" content="${csp}">`;

// Matches a previously-stamped block (comment + tag) so re-runs replace it.
const EXISTING = new RegExp(
  `[ \\t]*<!-- ${CSP_MARKER}[\\s\\S]*?-->\\s*<meta http-equiv="Content-Security-Policy"[^>]*>\\n?`,
  'g'
);
// Also catches a bare hand-written CSP meta tag with no marker comment.
const BARE = /[ \t]*<meta http-equiv="Content-Security-Policy"[^>]*>\n?/gi;

const deployed = fs
  .readdirSync(ROOT)
  .filter((f) => f.endsWith('.html'))
  .filter((f) => !PRUNED_FROM_PRODUCTION.includes(f))
  .sort();

const csp = buildCsp();
let changed = 0;
const problems = [];

for (const file of deployed) {
  const full = path.join(ROOT, file);
  const original = fs.readFileSync(full, 'utf8');

  let body = original.replace(EXISTING, '').replace(BARE, '');

  // Anchor on <meta charset>; the character encoding declaration must appear in
  // the first 1024 bytes, so nothing may be inserted ahead of it.
  const charset = body.match(/<meta\s+charset=[^>]*>/i);
  if (!charset) {
    problems.push(`${file}: no <meta charset> to anchor the policy to`);
    continue;
  }
  const at = body.indexOf(charset[0]) + charset[0].length;
  const next = `${body.slice(0, at)}\n${BLOCK(csp)}${body.slice(at)}`;

  if (next !== original) {
    changed++;
    if (CHECK_ONLY) {
      problems.push(`${file}: CSP missing or out of date`);
    } else {
      fs.writeFileSync(full, next);
    }
  }
}

console.log(`policy: ${csp.length} chars, ${csp.split(';').length} directives`);
console.log(`pages:  ${deployed.length} deployed (${PRUNED_FROM_PRODUCTION.length} pruned from production, skipped)`);

if (problems.length) {
  console.error('\nPROBLEMS:');
  for (const p of problems) console.error('  ' + p);
  process.exit(1);
}
console.log(CHECK_ONLY ? 'check: every deployed page carries the current policy' : `applied: ${changed} page(s) updated`);
