-- The Intelligence Layer: Metrics Engine (SQL, deterministic) → Insight Engine
-- (edge function, deterministic) → Gemini (narration only). See the plan doc
-- section "Architecture — revised to a three-layer pipeline" for the full
-- design and the rationale for each schema decision below.
--
-- This migration adds three tables and one SQL function. It does not touch
-- any existing table.

-- ── intelligence_reports — one row per generated Daily/Weekly/Monthly report ──
CREATE TABLE IF NOT EXISTS intelligence_reports (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_type               text NOT NULL CHECK (report_type IN ('daily','weekly','monthly')),
  period_start              date NOT NULL,
  period_end                date NOT NULL,
  generated_at              timestamptz NOT NULL DEFAULT now(),
  status                    text NOT NULL DEFAULT 'generated' CHECK (status IN ('generated','failed')),
  title                     text,
  executive_summary         text,
  body_markdown             text,
  -- The exact deterministic data Gemini was given — the audit trail that
  -- makes "never invent a number" independently checkable after the fact.
  metrics_snapshot          jsonb,
  mentioned_districts       text[] NOT NULL DEFAULT '{}',
  mentioned_property_types  text[] NOT NULL DEFAULT '{}',
  model_used                text,
  error_message             text,
  search_vector             tsvector GENERATED ALWAYS AS (
                               to_tsvector('english', coalesce(title,'') || ' ' || coalesce(body_markdown,''))
                             ) STORED,
  created_at                timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_intelligence_reports_type_period ON intelligence_reports(report_type, period_start DESC);
CREATE INDEX IF NOT EXISTS idx_intelligence_reports_generated   ON intelligence_reports(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_intelligence_reports_search      ON intelligence_reports USING GIN(search_vector);
CREATE INDEX IF NOT EXISTS idx_intelligence_reports_districts   ON intelligence_reports USING GIN(mentioned_districts);
CREATE INDEX IF NOT EXISTS idx_intelligence_reports_types       ON intelligence_reports USING GIN(mentioned_property_types);

COMMENT ON TABLE intelligence_reports IS
  'AI-narrated Daily/Weekly/Monthly reports. The narrative (body_markdown) is generated by Gemini from metrics_snapshot and the insights linked via report_insights — Gemini explains and connects, it never computes the numbers itself.';

-- ── intelligence_insights — the persistent, cross-day Insight Engine layer ──
-- One row per detected, tracked condition (a district demand spike, a
-- listing's CTR decline, etc). Opened when a metric crosses a statistical
-- significance bar, updated while it persists, resolved with hysteresis
-- (a lower bar than the one that opened it, to avoid flapping on noise
-- right at the boundary). See generate-intelligence-report's Insight Engine
-- step for the detection/update/resolve logic — this table is pure storage.
CREATE TABLE IF NOT EXISTS intelligence_insights (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type                     text NOT NULL CHECK (type IN (
                             'demand_spike','supply_shortage','ctr_decline','ctr_improvement',
                             'high_performing_listing','low_performing_listing','ux_anomaly',
                             'conversion_anomaly','search_trend','price_trend'
                           )),
  severity                 text NOT NULL DEFAULT 'medium' CHECK (severity IN ('low','medium','high','critical')),
  -- Statistical confidence this is real signal (derived from z-score
  -- magnitude), distinct from severity (business impact) — a low-severity,
  -- high-confidence blip and a high-severity, low-confidence possible
  -- problem should read differently, which one number can't carry.
  confidence               numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),
  -- Flat, filterable dimension columns rather than relying on `evidence`
  -- jsonb for this — matches this schema's existing convention
  -- (search_events/listing_events/ui_events all do the same) so "every
  -- open insight about Sisattanak" is a plain indexed WHERE, not a jsonb
  -- parse over every row.
  metric_key               text NOT NULL,
  dimension_district       text,
  dimension_property_type  text,
  dimension_property_id    uuid REFERENCES properties(id) ON DELETE SET NULL,
  title                    text NOT NULL,
  summary                  text,
  evidence                 jsonb NOT NULL,
  -- Optional — only fills in cleanly for simple, single-cause insights
  -- (a low-CTR listing → "weak cover photo"). The report's own
  -- "AI Recommendations" section synthesizes across the whole active
  -- insight set and is not just a concatenation of these fields.
  recommendation           text,
  trend                    text NOT NULL DEFAULT 'emerging' CHECK (trend IN ('emerging','strengthening','stable','weakening','resolved')),
  first_seen               date NOT NULL,
  last_seen                date NOT NULL,
  resolved_at               timestamptz,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_intelligence_insights_open        ON intelligence_insights(resolved_at) WHERE resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_intelligence_insights_key         ON intelligence_insights(metric_key, dimension_district, dimension_property_type, dimension_property_id);
CREATE INDEX IF NOT EXISTS idx_intelligence_insights_type        ON intelligence_insights(type);
CREATE INDEX IF NOT EXISTS idx_intelligence_insights_district    ON intelligence_insights(dimension_district);
CREATE INDEX IF NOT EXISTS idx_intelligence_insights_prop_type   ON intelligence_insights(dimension_property_type);
CREATE INDEX IF NOT EXISTS idx_intelligence_insights_first_seen  ON intelligence_insights(first_seen DESC);

COMMENT ON TABLE intelligence_insights IS
  'Deterministically detected, cross-day-tracked conditions (demand spikes, CTR declines, etc). Written only by the Insight Engine step of generate-intelligence-report, never by Gemini — this is the "code decides what matters" layer.';

-- Reuses the existing global update_updated_at() trigger function (defined
-- in 20260622000000_engagement_metrics.sql) rather than redefining it.
DROP TRIGGER IF EXISTS trg_intelligence_insights_updated_at ON intelligence_insights;
CREATE TRIGGER trg_intelligence_insights_updated_at
  BEFORE UPDATE ON intelligence_insights
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ── report_insights — which insights a report discussed, and how ──────────
-- Powers the Intelligence Timeline (an insight's full history: first seen,
-- every report that mentioned it, when it resolved) without overloading
-- `evidence` with relational facts it isn't meant to hold.
CREATE TABLE IF NOT EXISTS report_insights (
  report_id  uuid NOT NULL REFERENCES intelligence_reports(id) ON DELETE CASCADE,
  insight_id uuid NOT NULL REFERENCES intelligence_insights(id) ON DELETE CASCADE,
  role       text NOT NULL CHECK (role IN (
               'biggest_story','marketplace','buyer_behavior','property_performance',
               'product_insight','opportunity','recommendation_basis','mentioned'
             )),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (report_id, insight_id, role)
);

CREATE INDEX IF NOT EXISTS idx_report_insights_insight ON report_insights(insight_id);

COMMENT ON TABLE report_insights IS
  'Join table recording which insights each report discussed and in what role. Drives the NEW/CONTINUING/RESOLVED grouping in the UI and the per-insight Intelligence Timeline.';

-- ── RLS — staff-only read, no client-role write at all ─────────────────────
-- generate-intelligence-report writes with the Supabase service-role key,
-- which bypasses RLS by design, so every client role (including staff) only
-- ever has read access to these three tables via the API — matches the
-- read-only posture already used for search_events/listing_events/ui_events.
ALTER TABLE intelligence_reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Staff read intelligence_reports" ON intelligence_reports;
CREATE POLICY "Staff read intelligence_reports"
  ON intelligence_reports FOR SELECT TO authenticated
  USING (is_pintag_staff(auth.uid()));

ALTER TABLE intelligence_insights ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Staff read intelligence_insights" ON intelligence_insights;
CREATE POLICY "Staff read intelligence_insights"
  ON intelligence_insights FOR SELECT TO authenticated
  USING (is_pintag_staff(auth.uid()));

ALTER TABLE report_insights ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Staff read report_insights" ON report_insights;
CREATE POLICY "Staff read report_insights"
  ON report_insights FOR SELECT TO authenticated
  USING (is_pintag_staff(auth.uid()));

-- ── Metrics Engine — the deterministic aggregation layer ───────────────────
-- Returns one row per calendar day in [p_start, p_end], each a self-contained
-- jsonb snapshot of that day computed from the five existing event tables.
-- Zero judgment happens here — every number is a plain count/ratio. The
-- Insight Engine (TypeScript, in the edge function) decides what's
-- significant; this function only ever answers "what happened."
--
-- Supply (active listing counts by district/type) is deliberately NOT part
-- of this function — Pintag has no historical point-in-time supply data,
-- only a current snapshot, so pretending it has a daily time series would
-- be misleading. The edge function fetches current supply with one plain
-- query of its own when it needs it (e.g. for demand-vs-supply opportunity
-- detection), separately from this day-by-day time series.
CREATE OR REPLACE FUNCTION intelligence_daily_metrics(p_start date, p_end date)
RETURNS TABLE(day date, metrics jsonb)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  WITH days AS (
    SELECT generate_series(p_start, p_end, interval '1 day')::date AS d
  ),

  -- ── search_events ─────────────────────────────────────────────────────
  search_totals AS (
    SELECT created_at::date AS d,
      count(*) AS total,
      count(*) FILTER (WHERE result_count = 0) AS zero_result
    FROM search_events
    WHERE created_at::date BETWEEN p_start AND p_end
    GROUP BY 1
  ),
  search_by_district AS (
    SELECT d, jsonb_object_agg(district, cnt) AS obj FROM (
      SELECT created_at::date AS d, district, count(*) AS cnt
      FROM search_events
      WHERE created_at::date BETWEEN p_start AND p_end AND district IS NOT NULL
      GROUP BY 1, district
    ) x GROUP BY d
  ),
  search_by_type AS (
    SELECT d, jsonb_object_agg(property_type, cnt) AS obj FROM (
      SELECT created_at::date AS d, property_type, count(*) AS cnt
      FROM search_events
      WHERE created_at::date BETWEEN p_start AND p_end AND property_type IS NOT NULL
      GROUP BY 1, property_type
    ) x GROUP BY d
  ),
  search_by_tx AS (
    SELECT d, jsonb_object_agg(transaction_type, cnt) AS obj FROM (
      SELECT created_at::date AS d, transaction_type, count(*) AS cnt
      FROM search_events
      WHERE created_at::date BETWEEN p_start AND p_end AND transaction_type IS NOT NULL
      GROUP BY 1, transaction_type
    ) x GROUP BY d
  ),

  -- ── listing_events ────────────────────────────────────────────────────
  listing_totals AS (
    SELECT created_at::date AS d,
      count(*) FILTER (WHERE event_type = 'impression') AS impressions,
      count(*) FILTER (WHERE event_type = 'click')      AS clicks,
      count(*) FILTER (WHERE event_type = 'view')        AS views
    FROM listing_events
    WHERE created_at::date BETWEEN p_start AND p_end
    GROUP BY 1
  ),
  views_by_district AS (
    SELECT d, jsonb_object_agg(district_en, cnt) AS obj FROM (
      SELECT le.created_at::date AS d, p.district_en, count(*) AS cnt
      FROM listing_events le JOIN properties p ON p.id = le.property_id
      WHERE le.created_at::date BETWEEN p_start AND p_end AND le.event_type = 'view' AND p.district_en IS NOT NULL
      GROUP BY 1, p.district_en
    ) x GROUP BY d
  ),
  views_by_type AS (
    SELECT d, jsonb_object_agg(property_type, cnt) AS obj FROM (
      SELECT le.created_at::date AS d, p.property_type, count(*) AS cnt
      FROM listing_events le JOIN properties p ON p.id = le.property_id
      WHERE le.created_at::date BETWEEN p_start AND p_end AND le.event_type = 'view' AND p.property_type IS NOT NULL
      GROUP BY 1, p.property_type
    ) x GROUP BY d
  ),

  -- ── lead_events / leads ───────────────────────────────────────────────
  lead_event_totals AS (
    SELECT created_at::date AS d,
      count(*) FILTER (WHERE event_type = 'whatsapp_click') AS whatsapp_clicks,
      count(*) FILTER (WHERE event_type = 'call_click')      AS call_clicks
    FROM lead_events
    WHERE created_at::date BETWEEN p_start AND p_end
    GROUP BY 1
  ),
  leads_created_totals AS (
    SELECT created_at::date AS d, count(*) AS n
    FROM leads WHERE created_at::date BETWEEN p_start AND p_end
    GROUP BY 1
  ),
  -- Approximation, disclosed: leads has no status-change history, so
  -- "closed/lost that day" is read as "currently closed/lost, last touched
  -- that day" — the best available signal without a separate history table.
  leads_closed_totals AS (
    SELECT updated_at::date AS d, count(*) AS n
    FROM leads WHERE status = 'closed' AND updated_at::date BETWEEN p_start AND p_end
    GROUP BY 1
  ),
  leads_lost_totals AS (
    SELECT updated_at::date AS d, count(*) AS n
    FROM leads WHERE status = 'lost' AND updated_at::date BETWEEN p_start AND p_end
    GROUP BY 1
  ),

  -- ── ui_events ─────────────────────────────────────────────────────────
  ui_totals AS (
    SELECT created_at::date AS d,
      count(DISTINCT session_id) FILTER (WHERE session_id IS NOT NULL) AS sessions_total,
      count(*) FILTER (WHERE element_id LIKE 'gallery-%')  AS gallery_events,
      count(*) FILTER (WHERE element_id = 'share-property') AS share_events,
      count(*) FILTER (WHERE element_id = 'favorite-property') AS favorite_events,
      count(*) FILTER (WHERE element_id IN ('map-open-link','map-embed','view-toggle-map')) AS map_events
    FROM ui_events
    WHERE created_at::date BETWEEN p_start AND p_end
    GROUP BY 1
  ),
  filter_usage AS (
    SELECT d, jsonb_object_agg(element_id, cnt) AS obj FROM (
      SELECT created_at::date AS d, element_id, count(*) AS cnt
      FROM ui_events
      WHERE created_at::date BETWEEN p_start AND p_end AND element_type IN ('filter','select','toggle')
      GROUP BY 1, element_id
    ) x GROUP BY d
  ),
  ui_element_counts AS (
    SELECT d, jsonb_object_agg(element_id, cnt) AS obj FROM (
      SELECT created_at::date AS d, element_id, count(*) AS cnt
      FROM ui_events
      WHERE created_at::date BETWEEN p_start AND p_end
      GROUP BY 1, element_id
    ) x GROUP BY d
  ),

  -- ── property performance leaderboards ────────────────────────────────
  top_by_views AS (
    SELECT d, jsonb_agg(row ORDER BY (row->>'views')::int DESC) AS arr FROM (
      SELECT le.created_at::date AS d,
        jsonb_build_object('property_id', p.id, 'title', coalesce(p.title_en, p.title_lo), 'views', count(*)) AS row
      FROM listing_events le JOIN properties p ON p.id = le.property_id
      WHERE le.created_at::date BETWEEN p_start AND p_end AND le.event_type = 'view'
      GROUP BY le.created_at::date, p.id, p.title_en, p.title_lo
    ) x GROUP BY d
  ),
  ctr_by_property AS (
    SELECT le.created_at::date AS d, p.id, coalesce(p.title_en, p.title_lo) AS title,
      count(*) FILTER (WHERE le.event_type = 'impression') AS impressions,
      count(*) FILTER (WHERE le.event_type = 'click')      AS clicks
    FROM listing_events le JOIN properties p ON p.id = le.property_id
    WHERE le.created_at::date BETWEEN p_start AND p_end AND le.event_type IN ('impression','click')
    GROUP BY 1, p.id, title
  ),
  top_by_ctr AS (
    -- Minimum-impressions floor avoids "100% CTR" noise from a listing
    -- shown once and clicked once.
    SELECT d, jsonb_agg(row ORDER BY (row->>'ctr')::numeric DESC) AS arr FROM (
      SELECT d,
        jsonb_build_object('property_id', id, 'title', title, 'impressions', impressions,
                            'clicks', clicks, 'ctr', round(clicks::numeric / impressions, 3)) AS row
      FROM ctr_by_property WHERE impressions >= 5
    ) x GROUP BY d
  ),
  impressions_no_leads AS (
    SELECT cp.d,
      jsonb_agg(jsonb_build_object('property_id', cp.id, 'title', cp.title, 'impressions', cp.impressions)) AS arr
    FROM ctr_by_property cp
    WHERE cp.impressions >= 5
      AND NOT EXISTS (
        SELECT 1 FROM lead_events le
        WHERE le.listing_id = cp.id AND le.created_at::date = cp.d
      )
    GROUP BY cp.d
  )

  SELECT days.d,
    jsonb_build_object(
      'search', jsonb_build_object(
        'total', coalesce(st.total, 0),
        'zero_result', coalesce(st.zero_result, 0),
        'by_district', coalesce(sbd.obj, '{}'::jsonb),
        'by_property_type', coalesce(sbt.obj, '{}'::jsonb),
        'by_transaction_type', coalesce(sbtx.obj, '{}'::jsonb)
      ),
      'listing_impressions', coalesce(lt.impressions, 0),
      'listing_clicks', coalesce(lt.clicks, 0),
      'listing_views', coalesce(lt.views, 0),
      'listing_ctr', CASE WHEN coalesce(lt.impressions,0) > 0
                       THEN round(lt.clicks::numeric / lt.impressions, 3) ELSE 0 END,
      'views_by_district', coalesce(vbd.obj, '{}'::jsonb),
      'views_by_property_type', coalesce(vbt.obj, '{}'::jsonb),
      'whatsapp_clicks', coalesce(let.whatsapp_clicks, 0),
      'call_clicks', coalesce(let.call_clicks, 0),
      'leads_created', coalesce(lct.n, 0),
      'leads_closed', coalesce(lclt.n, 0),
      'leads_lost', coalesce(llt.n, 0),
      'sessions_total', coalesce(ut.sessions_total, 0),
      'avg_listings_viewed_per_session', CASE WHEN coalesce(ut.sessions_total,0) > 0
                       THEN round(lt.views::numeric / ut.sessions_total, 2) ELSE 0 END,
      'gallery_events', coalesce(ut.gallery_events, 0),
      'share_events', coalesce(ut.share_events, 0),
      'favorite_events', coalesce(ut.favorite_events, 0),
      'map_events', coalesce(ut.map_events, 0),
      'filter_usage', coalesce(fu.obj, '{}'::jsonb),
      'ui_element_counts', coalesce(uec.obj, '{}'::jsonb),
      'top_listings_by_views', coalesce(tbv.arr, '[]'::jsonb),
      'top_listings_by_ctr', coalesce(tbc.arr, '[]'::jsonb),
      'impressions_no_leads', coalesce(inl.arr, '[]'::jsonb)
    ) AS metrics
  FROM days
  LEFT JOIN search_totals st        ON st.d = days.d
  LEFT JOIN search_by_district sbd  ON sbd.d = days.d
  LEFT JOIN search_by_type sbt      ON sbt.d = days.d
  LEFT JOIN search_by_tx sbtx       ON sbtx.d = days.d
  LEFT JOIN listing_totals lt       ON lt.d = days.d
  LEFT JOIN views_by_district vbd   ON vbd.d = days.d
  LEFT JOIN views_by_type vbt       ON vbt.d = days.d
  LEFT JOIN lead_event_totals let   ON let.d = days.d
  LEFT JOIN leads_created_totals lct  ON lct.d = days.d
  LEFT JOIN leads_closed_totals lclt  ON lclt.d = days.d
  LEFT JOIN leads_lost_totals llt     ON llt.d = days.d
  LEFT JOIN ui_totals ut            ON ut.d = days.d
  LEFT JOIN filter_usage fu         ON fu.d = days.d
  LEFT JOIN ui_element_counts uec   ON uec.d = days.d
  LEFT JOIN top_by_views tbv        ON tbv.d = days.d
  LEFT JOIN top_by_ctr tbc          ON tbc.d = days.d
  LEFT JOIN impressions_no_leads inl ON inl.d = days.d
  ORDER BY days.d;
$$;

COMMENT ON FUNCTION intelligence_daily_metrics IS
  'The Metrics Engine — one deterministic jsonb snapshot per calendar day, zero judgment. Called by generate-intelligence-report; the Insight Engine (TypeScript) decides significance from this output, never SQL.';
